import { APP_VERSION } from "@/shared/config/version";

/**
 * App footer — shows the current version (from the git semantic version,
 * generated by scripts/version.ts) centered at the bottom of every page.
 * pb-20 clears the fixed mobile BottomNav; lg:hidden nav means pb-8 on desktop.
 */
export function SiteFooter() {
  return (
    <footer className="bg-surface mt-8 px-4 pb-20 pt-4 lg:pb-8">
      <p className="text-label-sm font-label-sm text-on-surface-variant text-center">
        Core Rental · {APP_VERSION}
      </p>
    </footer>
  );
}
