allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@ai-sdk/anthropic@4.0.46"
  - "@ai-sdk/provider-utils@5.0.34"
  - "@ai-sdk/provider@4.0.9"
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
