/**
 * Build-time version source (git semantic version). Reads the highest
 * semver git tag (git describe --tags --abbrev=0) and writes it to
 * src/shared/config/version.ts so the footer can display the current
 * app version. Falls back to package.json's version when git tags are
 * unavailable (e.g. Vercel's shallow clone).
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const OUT = join(process.cwd(), "src", "shared", "config", "version.ts");

function gitTag(): string | null {
  try {
    const tag = execSync("git describe --tags --abbrev=0", {
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
    return tag.length > 0 ? tag : null;
  } catch {
    return null; // no tags / not a git checkout
  }
}

function packageVersion(): string {
  try {
    const pkg = JSON.parse(readFileSync(join(process.cwd(), "package.json"), "utf8")) as {
      version?: string;
    };
    return pkg.version ?? "0.0.0";
  } catch {
    return "0.0.0";
  }
}

const version = gitTag() ?? packageVersion();

writeFileSync(
  OUT,
  `// Auto-generated by scripts/version.ts (git semantic version). Do not edit.\nexport const APP_VERSION = ${JSON.stringify(version)};\n`,
);

console.log(`version: ${version}`);
